services:

  db:
    image: postgres:16
    container_name: postgres_db2
    restart: always
    environment:
      POSTGRES_DB: support
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello2020
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: django_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=*
      - DB_NAME=support
      - DB_USER=postgres
      - DB_PASSWORD=hello2020
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: vue_frontend
    restart: always
    ports:
      - "80:80"

volumes:
  postgres_data: