# Generated by Django 6.0.5 on 2026-05-23 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('isbn', models.CharField(max_length=13)),
                ('genre', models.CharField(choices=[('fa', 'Fantacy'), ('fi', 'Fiction'), ('ro', 'Romance')], default='fi', max_length=2)),
                ('pub_date', models.DateField()),
                ('status', models.CharField(choices=[('pu', 'Published'), ('re', 'Review')], default='re', max_length=2)),
                ('mrp', models.IntegerField()),
                ('copies_sold', models.IntegerField(default=0)),
                ('royality_earned', models.IntegerField(default=0)),
                ('royality_paid', models.IntegerField(default=0)),
                ('royality_pending', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('op', 'Open'), ('pr', 'In-progress'), ('re', 'Resolved'), ('cl', 'Closed')], default='pr', max_length=2)),
                ('response', models.CharField(blank=True, max_length=512, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.book')),
            ],
        ),
    ]
