# Generated by Django 6.0.5 on 2026-05-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
