# Generated by Django 6.0.5 on 2026-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_book_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='mrp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
